### ISSUE TITLE
Poopy Butthole

### ISSUE THREAD

**Issue by Poilikis** [Mudilist/Ultimate-Calculator-Ripoff-V.1-#1]
![Ches](https://user-images.githubusercontent.com/98619275/164080013-23898a11-4513-4e7b-bc75-e4ebc34ab322.png)

**Comment by Mudilist** [comment]
> Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee Pee moose ![Dvd](https://user-images.githubusercontent.com/98619275/164079778-0ebe2688-726e-4816-ae17-3ddfaf16d30f.svg)
